// <auto-generated />
using System;
using Massive.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Massive.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516011222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Massive.Api.Models.Company", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("text");

                    b.Property<int>("AltKm")
                        .HasColumnType("integer");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Founded")
                        .HasColumnType("integer");

                    b.Property<string>("Hq")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Sectors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double?>("YOffset")
                        .HasColumnType("double precision");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ticker");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Massive.Api.Models.NewsArticle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ArticleUrl")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tickers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublishedUtc");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("Massive.Api.Models.Quote", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("text");

                    b.Property<decimal?>("Change")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ChangePct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Open")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Ticker");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Massive.Api.Models.Quote", b =>
                {
                    b.HasOne("Massive.Api.Models.Company", "Company")
                        .WithOne("Quote")
                        .HasForeignKey("Massive.Api.Models.Quote", "Ticker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Massive.Api.Models.Company", b =>
                {
                    b.Navigation("Quote");
                });
#pragma warning restore 612, 618
        }
    }
}
